Yts 1 adding models
Tayyab-athar-1998/yts pull request #1
Opened 2020-12-16 13:01 UTC by Tayyab-athar-1998

2020-12-21 04:44 UTC, Tayyab-athar-1998 commented
TODO: remove has_many: :through relations after having discusssion with @Usman bhai

2020-12-22 05:36 UTC, usmansaleem001 requested changes

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215195738_create_users.rb
> +      t.string :email
why there is no index on email?

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215194333_create_movies.rb
> +      t.boolean :is_featured
shouldn't these have indexes?

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215195823_create_actors.rb
> +      t.string :name
what is the default value and max char size?

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215195823_create_actors.rb
> +    create_table :actors do |t|
why an actor has a  separate model rather than a role in the user model?

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215195949_create_genres.rb
> +    create_table :genres do |t|
it should be a serialized column.

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215200016_create_languages.rb
> +class CreateLanguages < ActiveRecord::Migration[5.1]
same goes for this.

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215201519_create_comments.rb
> +    create_table :comments do |t|
user refrences?

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215201531_create_reviews.rb
> +      t.string :content
don't we need to add user_id here?

2020-12-22 05:36 UTC, usmansaleem001 commented on db/migrate/20201215201633_create_movie_roles.rb
> +      t.string :role_played
where is actor _id?

2020-12-22 05:50 UTC, Tayyab-athar-1998 commented on db/migrate/20201215195823_create_actors.rb
> +    create_table :actors do |t|
I was following YTS were actors were not the registered users and have only name and a display value

2020-12-22 05:57 UTC, Tayyab-athar-1998 commented on db/migrate/20201215201633_create_movie_roles.rb
> +      t.string :role_played
@usmansaleem001  bhai I created model separately and then wrote separate migrations to add columns for associations

2020-12-22 05:59 UTC, Tayyab-athar-1998 commented on db/migrate/20201215195949_create_genres.rb
> +    create_table :genres do |t|
Okay

2020-12-22 11:37 UTC, Tayyab-athar-1998 commented on db/migrate/20201215201531_create_reviews.rb
> +      t.string :content
Have a separate migration in followup commits for associations

2020-12-22 11:37 UTC, Tayyab-athar-1998 commented on db/migrate/20201215201519_create_comments.rb
> +    create_table :comments do |t|
Have a separate migration in followup commits for associations

2020-12-22 11:37 UTC, Tayyab-athar-1998 commented on db/migrate/20201215200016_create_languages.rb
> +class CreateLanguages < ActiveRecord::Migration[5.1]
Have been removed in follow up commits already

2020-12-22 11:38 UTC, Tayyab-athar-1998 commented on db/migrate/20201215195738_create_users.rb
> +      t.string :email
adding

2020-12-22 11:38 UTC, Tayyab-athar-1998 commented on db/migrate/20201215194333_create_movies.rb
> +      t.boolean :is_featured
adding

2020-12-22 11:38 UTC, Tayyab-athar-1998 commented on db/migrate/20201215195823_create_actors.rb
> +      t.string :name
added a validation in followup commit so that it is not empty and didn't setup a max char size

2020-12-24 18:44 UTC, usmansaleem001 approved these changes

2020-12-26 06:34 UTC, merged