Yts-2 Adding validations to models and seed data
Tayyab-athar-1998/yts pull request #2
Opened 2020-12-17 01:35 UTC by Tayyab-athar-1998

2020-12-21 13:44 UTC, IDaniyal approved these changes

2020-12-21 13:44 UTC, IDaniyal commented on app/models/movie.rb
> +  def release_date_is_date
```suggestion
  def valid_release_date?
```

2020-12-24 18:50 UTC, usmansaleem001 requested changes

2020-12-24 18:50 UTC, usmansaleem001 commented on app/models/movie.rb
> +  validates :languages, presence: true, inclusion: {
might need to revisit this.

2020-12-24 18:50 UTC, usmansaleem001 commented on app/models/movie_role.rb
> +  enum allowed_roles: %w[actor director]
```suggestion
  enum roles: %w[actor director]
```

2020-12-24 18:50 UTC, usmansaleem001 commented on app/models/user.rb
>    has_many :comments, through: :likes, source: :likeable, source_type: 'Comment'
read about counter cache and implement here.

2020-12-28 07:35 UTC, Tayyab-athar-1998 commented on app/models/user.rb
>    has_many :comments, through: :likes, source: :likeable, source_type: 'Comment'
implemented it for normal associations looking into how to implement it for polymorphic associations

2020-12-28 07:53 UTC, Tayyab-athar-1998 commented
TODO:
1- Style admin panel views and move them from erb to haml.
2- Look into counter caching for polymorphic association and implement it in.
3- Remove unused actions from movie resource after it movie page implementation is complete.

2021-01-05 09:17 UTC, merged