YTS-3 creating home page
Tayyab-athar-1998/yts pull request #3
Opened 2020-12-21 04:37 UTC by Tayyab-athar-1998

2020-12-21 04:39 UTC, Tayyab-athar-1998 commented
TODO: Move styles from application.scss to home.scss(classes in home.scss were not applying on the view)

2020-12-21 05:42 UTC, Tayyab-athar-1998 commented
> TODO: Move styles from application.scss to home.scss(classes in home.scss were not applying on the view)

Done!

2020-12-21 13:31 UTC, IDaniyal commented on app/controllers/home_controller.rb
> +    @movies_on_number_of_downlaods = Movie.order_by_number_of_downloads.take(4)
```suggestion
    @popular_movies = Movie.order_by_number_of_downloads.take(4)
```

2020-12-24 18:56 UTC, usmansaleem001 requested changes

2020-12-24 18:56 UTC, usmansaleem001 commented on app/controllers/home_controller.rb
> +    @movies_on_number_of_downlaods = Movie.order_by_number_of_downloads.take(4)
```suggestion
    @movies_on_number_of_downlaods = Movie.most_downloaded.take(4)
```

2020-12-24 18:56 UTC, usmansaleem001 commented on app/controllers/home_controller.rb
> +    @movies_on_number_of_downlaods = Movie.order_by_number_of_downloads.take(4)
move 4 to constant and use it.

2020-12-24 18:56 UTC, usmansaleem001 commented on app/models/movie.rb
>    serialize :video_quality
serialize should be on top.

2020-12-24 18:56 UTC, usmansaleem001 commented on app/views/home/index.html.haml
> +      =render partial: "shared/movie_row", locals: {movies: @movies_on_number_of_downlaods}
prefer single quotes

2020-12-24 18:56 UTC, usmansaleem001 commented on app/views/shared/_header.html.haml
> +      %a.nav-link{:herf => '#'} Home
new hash notation

2020-12-24 18:56 UTC, usmansaleem001 commented on app/views/shared/_header.html.haml
> +        %input.form-control.rounded-5{:placeholder => 'Quick search'}
new notation

2020-12-24 18:56 UTC, usmansaleem001 commented on app/views/shared/_movie_brick.html.haml
> +    %p{style: 'color: #919191'}
the style shouldn't be defined here.

2020-12-28 07:42 UTC, merged