YTS-5-Adding auth for users
Tayyab-athar-1998/yts pull request #5
Opened 2020-12-21 04:42 UTC by Tayyab-athar-1998

2020-12-21 04:42 UTC, Tayyab-athar-1998 commented
TODO: Apply styling on login and signup pages

2020-12-21 12:42 UTC, IDaniyal approved these changes

2020-12-24 18:58 UTC, usmansaleem001 requested changes

2020-12-24 18:58 UTC, usmansaleem001 commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
use one format... either haml or html

2020-12-26 09:19 UTC, Tayyab-athar-1998 commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
These files were automatically generated with devise. Will be updating them while working on login and sign up modal and forms.

2020-12-28 07:43 UTC, merged